name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install TA-Lib library
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libta-lib0-dev ta-lib

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run your bot
      run: python your_script.py