name: Build and Install Dependencies

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code from repository
        uses: actions/checkout@v2

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install system dependencies for TA-Lib
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential python3-dev libatlas-base-dev libta-lib-dev

      - name: Install Python dependencies from requirements.txt
        run: |
          pip install -r requirements.txt