name: Install Dependencies and Build

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # Checkout du code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Utilisation de Python 3.11

    - name: Install system dependencies for TA-Lib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libatlas-base-dev libta-lib0 libta-lib-dev

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt  # Installer les dépendances Python listées dans requirements.txt
        pip install TA-Lib  # Installer TA-Lib avec pip

    - name: Run tests
      run: |
        python -m unittest discover  # Exemple de test pour vérifier si tout fonctionne