name: Install Dependencies and Build

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # Checkout du code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Utilisation de Python 3.11

    - name: Install system dependencies for Python 3.11 and TA-Lib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3.11-dev libpython3.11-dev libatlas-base-dev libta-lib0 libta-lib-dev  # Installation de toutes les dépendances nécessaires

    - name: Upgrade pip to the latest version
      run: |
        pip install --upgrade pip  # Met à jour pip

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt  # Installer les dépendances Python listées dans requirements.txt
        pip install TA-Lib==0.4.17  # Installer une version stable de TA-Lib pour éviter les problèmes de compilation

    - name: Run tests
      run: |
        python -m unittest discover  # Exemple de test pour vérifier si tout fonctionne