name: Install Dependencies and Build

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # Récupération du code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11  # Assurez-vous d'utiliser une version compatible avec vos bibliothèques
    
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel

    - name: Install system dependencies for TA-Lib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libatlas-base-dev libta-lib0 libta-lib-dev

    - name: Manually build and install TA-Lib from source
      run: |
        curl -L http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz | tar xz
        cd ta-lib
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt  # Installer les dépendances Python listées dans requirements.txt
        pip install TA-Lib  # Installer la bibliothèque TA-Lib depuis pip

    - name: Run tests
      run: |
        python -m unittest discover  # Test pour vérifier si tout fonctionne