name: Install Dependencies and Build

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # Checkout du code du dépôt

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Utilisation de Python 3.10

    - name: Install system dependencies for TA-Lib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libatlas-base-dev libta-lib0 libta-lib-dev libpython3.10-dev
        sudo apt-get install -y libatlas-base-dev libta-lib-dev  # S'assurer d'avoir les bonnes versions des dépendances

    - name: Upgrade pip to the latest version
      run: |
        pip install --upgrade pip  # Met à jour pip

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt  # Installer les dépendances Python listées dans requirements.txt
        pip install TA-Lib==0.4.17  # Installer une version stable de TA-Lib

    - name: Run tests
      run: |
        python -m unittest discover  # Exemple de test pour vérifier si tout fonctionne