name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # Installer TA-Lib au niveau système
    - name: Install TA-Lib manually
      run: |
        sudo apt-get update
        sudo apt-get install -y gcc make wget
        wget http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz
        tar -xvzf ta-lib-0.4.0-src.tar.gz
        cd ta-lib
        ./configure --prefix=/usr
        make
        sudo make install

    # Vérifier si TA-Lib est installé correctement
    - name: Verify TA-Lib installation
      run: ldconfig -p | grep -i ta_lib

    # Installer les dépendances Python
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    # Lancer le bot
    - name: Run your bot
      run: gunicorn -w 4 -b 0.0.0.0:$PORT --keep-alive 120 --log-level debug bot2:app