name: CI Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Miniconda
      run: |
        wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
        bash Miniconda3-latest-Linux-x86_64.sh -b
        export PATH="$HOME/miniconda3/bin:$PATH"

    - name: Create conda environment and install dependencies
      run: |
        conda create --name trading-bot python=3.11 -y
        conda activate trading-bot
        conda install -c conda-forge ta-lib
        pip install -r requirements.txt

    - name: Run your bot
      run: gunicorn -w 4 -b 0.0.0.0:$PORT --keep-alive 120 --log-level debug bot2:app