name: Install Dependencies and Build

on:
  push:
    branches:
      - main

jobs:
  install_dependencies:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2  # Checkout du code du dépôt
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x  # Définir la version de Python que vous utilisez
    
    - name: Upgrade pip, setuptools, and wheel
      run: |
        python -m pip install --upgrade pip setuptools wheel
    
    - name: Install system dependencies for TA-Lib
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential python3-dev libatlas-base-dev libta-lib0 libta-lib-dev
    
    - name: Manually build and install TA-Lib
      run: |
        curl -L http://prdownloads.sourceforge.net/ta-lib/ta-lib-0.4.0-src.tar.gz | tar xz
        cd ta-lib
        ./configure --prefix=/usr
        make
        sudo make install
        cd ..
        pip install TA-Lib

    - name: Install Python dependencies
      run: |
        pip install -r requirements.txt  # Installer les dépendances Python listées dans requirements.txt
    
    - name: Run tests
      run: |
        python -m unittest discover  # Exemple de test pour vérifier si tout fonctionne